name: big-data.lab

services:
  hadoop-master:
    build:
      context: ./hadoop
    image: big-data.lab/hadoop
    container_name: hadoop-master
    restart: unless-stopped
    hostname: hadoop-master
    env_file:
      - path: ./.env
        required: false
    environment:
      MASTER: "hadoop-master"
    command: ["/usr/local/bin/entrypoint-master.sh"]
    ports:
      - 9870:9870    # HDFS NameNode UI
      - 8020:8020    # HDFS NameNode RPC
      - 8088:8088    # YARN ResourceManager UI
      - 8032:8032    # YARN ResourceManager AMI
      - 19888:19888  # MapReduce JobHistory Server UI
      - 10020:10020  # MapReduce JobHistory Server IPC
    volumes:
      - hadoop_master_data:/volumes/data
      - hadoop_master_logs:/volumes/logs
    networks: [net]

  hadoop-worker1:
    image: big-data.lab/hadoop
    container_name: hadoop-worker1
    depends_on:
      - hadoop-master
    restart: unless-stopped
    hostname: hadoop-worker1
    env_file:
      - path: ./.env
        required: false
    environment:
      MASTER: "hadoop-master"
      AM_RPC: "43210-43219"
    command: ["/usr/local/bin/entrypoint-worker.sh"]
    expose:
      - 9864  # HDFS DataNode UI
      - 8042  # YARN NodeManager UI
    ports:
      - 43210-43219:43210-43219  # MapReduce AM RPC
    volumes:
      - hadoop_worker1_data:/volumes/data
      - hadoop_worker1_logs:/volumes/logs
    networks: [net]

  hadoop-worker2:
    image: big-data.lab/hadoop
    container_name: hadoop-worker2
    depends_on:
      - hadoop-master
    restart: unless-stopped
    hostname: hadoop-worker2
    env_file:
      - path: ./.env
        required: false
    environment:
      MASTER: "hadoop-master"
      AM_RPC: "43220-43229"
    command: ["/usr/local/bin/entrypoint-worker.sh"]
    expose:
      - 9864  # HDFS DataNode UI
      - 8042  # YARN NodeManager UI
    ports:
      - 43220-43229:43220-43229  # MapReduce AM RPC
    volumes:
      - hadoop_worker2_data:/volumes/data
      - hadoop_worker2_logs:/volumes/logs
    networks: [net]

  hadoop-worker3:
    image: big-data.lab/hadoop
    container_name: hadoop-worker3
    depends_on:
      - hadoop-master
    restart: unless-stopped
    hostname: hadoop-worker3
    env_file:
      - path: ./.env
        required: false
    environment:
      MASTER: "hadoop-master"
      AM_RPC: "43230-43239"
    command: ["/usr/local/bin/entrypoint-worker.sh"]
    expose:
      - 9864  # HDFS DataNode UI
      - 8042  # YARN NodeManager UI
    ports:
      - 43230-43239:43230-43239  # MapReduce AM RPC
    volumes:
      - hadoop_worker3_data:/volumes/data
      - hadoop_worker3_logs:/volumes/logs
    networks: [net]

  nginx:
    build:
      context: ./nginx
    image: big-data.lab/nginx
    container_name: nginx
    depends_on: 
      - hadoop-master
      - hadoop-worker1
      - hadoop-worker2
      - hadoop-worker3
    restart: unless-stopped
    hostname: nginx
    ports:
      - 9864:9864  # HDFS DataNode UI
      - 8042:8042  # YARN NodeManager UI
    networks: [net]

  mysql:
    build:
      context: ./mysql
    image: big-data.lab/mysql
    container_name: mysql
    restart: unless-stopped
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [net]

  hive-metastore:
    build:
      context: .
      dockerfile: hive/Dockerfile
    image: big-data.lab/hive
    container_name: hive-metastore
    depends_on:
      - mysql
      - hadoop-master
    restart: unless-stopped
    hostname: hive-metastore
    environment:
      MASTER: "hadoop-master"
    command: ["/usr/local/bin/entrypoint-metastore.sh"]
    ports:
      - 9083:9083  # Metastore Thrift
    networks: [net]

  hive-server2:
    image: big-data.lab/hive
    container_name: hive-server2
    depends_on:
      - hive-metastore
      - hadoop-master
    restart: unless-stopped
    hostname: hive-server2
    environment:
      MASTER: "hadoop-master"
    command: ["/usr/local/bin/entrypoint-server2.sh"]
    ports:
      - 10000:10000  # HS2 Thrift
      - 10002:10002  # HS2 Web UI
    networks: [net]

volumes:
  hadoop_master_data:
  hadoop_master_logs:
  hadoop_worker1_data:
  hadoop_worker1_logs:
  hadoop_worker2_data:
  hadoop_worker2_logs:
  hadoop_worker3_data:
  hadoop_worker3_logs:
  mysql_data:

networks:
  net:
    driver: bridge
