worker_processes auto;

events {
    worker_connections 4096;
}

http {
    upstream hadoop-worker1-dn-ui {
        server hadoop-worker1:9864;
    }

    upstream hadoop-worker1-nm-ui {
        server hadoop-worker1:8042;
    }

    upstream hadoop-worker2-dn-ui {
        server hadoop-worker2:9864;
    }

    upstream hadoop-worker2-nm-ui {
        server hadoop-worker2:8042;
    }

    upstream hadoop-worker3-dn-ui {
        server hadoop-worker3:9864;
    }

    upstream hadoop-worker3-nm-ui {
        server hadoop-worker3:8042;
    }

    server {
        listen 9864;
        server_name hadoop-worker1;

        location / {
            proxy_pass http://hadoop-worker1-dn-ui;
        }
    }

    server {
        listen 8042;
        server_name hadoop-worker1;

        location / {
            proxy_pass http://hadoop-worker1-nm-ui;
        }
    }

    server {
        listen 9864;
        server_name hadoop-worker2;

        location / {
            proxy_pass http://hadoop-worker2-dn-ui;
        }
    }

    server {
        listen 8042;
        server_name hadoop-worker2;

        location / {
            proxy_pass http://hadoop-worker2-nm-ui;
        }
    }

    server {
        listen 9864;
        server_name hadoop-worker3;

        location / {
            proxy_pass http://hadoop-worker3-dn-ui;
        }
    }

    server {
        listen 8042;
        server_name hadoop-worker3;

        location / {
            proxy_pass http://hadoop-worker3-nm-ui;
        }
    }
}
